### ISSUE TITLE
Mapping tags offline

### ISSUE THREAD

**Issue by hoonkai** [berndpfrommer/tagslam#22]
Hi

I'm curious to know more about how the tags were mapped offline for your "TagSLAM loop closure" video. You mentioned they were mapped using a laser pointer (range finder?), but how did you measure inclination, distance, and other metrics with a laser pointer?

The doc [here](https://berndpfrommer.github.io/tagslam_web/measurements/) provides the following example `tagslam.yaml`:

```
coordinate_measurements:
  - tag6_z:
      tag: 6
      corner: 0
      length: 2.070
      noise: 0.010
      direction: [0.0, 0.0, 1.0]
  - tag17_z:
      tag: 17
      corner: 0
      length: 0.619
      noise: 0.010
      direction: [0.0, 0.0, 1.0]
```

How should `tag6_z` be interpreted? What does `length: 2.070` mean? Does it mean the corner 0 of tag 6 is 2.07m along the Z axis? In practice, how were the coordinates of the tags identified?

Thanks
