### ISSUE TITLE
When taking odometry to tagslam, the callback do not works

### ISSUE THREAD

**Issue by hncsfan1996** [berndpfrommer/tagslam#28]
I have specify the odometry topic and transformation from odometry to odom and others as the website https://berndpfrommer.github.io/tagslam_web/input_files/ shows. And I am confirmed that the time stamp of odometry and images is identical. But when I run tagslam,  the callback do not works.
Is there any advice for you ? Thank you.

**Comment by berndpfrommer** [comment]
Can you please post the console output of tagslam?
Also, do
```
rosnode info tagslam
```
(your tagslam node may have a different name). What topics is tagslam subscribing to? Is data coming on those topics (rostopic echo)?

**Comment by hncsfan1996** [comment]
Thank you very much for your reply. I made a .zip about my console output in two situations(image only and image with odom), and also my bag information. Could you please help me to solve it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "berndpfrommer/tagslam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 晚上11:20
***@***.***&gt;;
抄送:&nbsp;"the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [berndpfrommer/tagslam] When taking odometry to tagslam, the callback do not works (#28)





 
Can you please post the console output of tagslam?
 Also, do
 rosnode info tagslam  
(your tagslam node may have a different name). What topics is tagslam subscribing to? Is data coming on those topics (rostopic echo)?

**Comment by berndpfrommer** [comment]
Not sure where that zip file of yours went. I don't see it anywhere. If you already want to send me files, send them to bernd dot pfrommer at gmail dot com. Please send all your yaml files, the launch files you are using and a rosbag with the odometry and images. To keep the rosbag size to a minimum record just a couple of seconds. That should be enough to diagnose the problem.

**Comment by berndpfrommer** [comment]
Odom timestamps:
```
---
seq: 46
stamp: 
  secs: 1617186351
  nsecs: 976934003
frame_id: "odom"
---
seq: 47
stamp: 
  secs: 1617186352
  nsecs:  20548998
frame_id: "odom"
---
seq: 48
stamp: 
  secs: 1617186352
  nsecs:  67111565
frame_id: "odom"
```

Tag detection time stamps (those come from the images):
```
---
seq: 1176
stamp: 
  secs: 1617186351
  nsecs: 970810860
frame_id: "usb_cam"
---
seq: 1177
stamp: 
  secs: 1617186352
  nsecs:  32014453
frame_id: "usb_cam"
---
seq: 1178
stamp: 
  secs: 1617186352
  nsecs:  63741078
frame_id: "usb_cam"
---

```
