### ISSUE TITLE
Tagslam gives bayes tree node not found when I try to tune the algorithm for the bag file of my setup.

### ISSUE THREAD

**Issue by dt1729** [berndpfrommer/tagslam#33]
Setup:  Markers are placed in a gazebo simulation with turtle bot and odometry is fed from the simul itself. I have given information about two markers in the tagslam.yaml file but with respect to the global coordinate frame of gazebosim. 

It gives me this error that I'm trying to understand: 
``` 
[ERROR] [1674501247.977188733]: /tagslam: Requested the BayesTree clique for a key that is not in the BayesTree
[tagslam-1] process has died [pid 9562, exit code 255, cmd /home/dt/AddverbWork/slamalgos/tagslam_ws/devel/lib/tagslam/tagslam_node __name:=tagslam __log:=/home/dt/.ros/log/ea0002dc-9b51-11ed-997c-91c581871bdd/tagslam-1.log].
log file: /home/dt/.ros/log/ea0002dc-9b51-11ed-997c-91c581871bdd/tagslam-1*.log
````

When I increase the   minimum_viewing_angle parameter this error goes away, however I'm looking for a better way to optimise and find these parameters. Any insights and help is appreciated, cheers.

**Comment by dt1729** [comment]
My tagslam.yaml file: 


```
tagslam_parameters:
  optimizer_mode: fast
  minimum_viewing_angle: 35.0
  max_num_incremental_opt: 100
  pixel_noise: 2.0
  max_subgraph_error: 50.0
  subgraph_abs_prior_position_noise: 0.1
  subgraph_abs_prior_rotation_noise: 0.1
  use_approximate_sync: true
body_defaults:
  position_noise: 0.05
  rotation_noise: 0.01
default_body: perch
bodies:
 - perch:
    is_static: true
    default_tag_size: 1.0
    pose:
      position:
        x: -1.05
        y: 11.66
        z: 2.5
      rotation:
        x: 0
        y: 0
        z: 0
      position_noise:
        x: 0.0001
        y: 0.0001
        z: 0.0001
      rotation_noise:
        x: 1.0e-05
        y: 1.0e-05
        z: 1.0e-05
    type: simple
    tags:
      - id: 21
        size: 1.0
        pose:
          position:
            x: 0
            y: 0
            z: 0
          rotation:
            x: 1.57
            y: 0
            z: 0
          position_noise:
            x: 0.0001
            y: 0.0001
            z: 0.0001
          rotation_noise:
            x: 1.0e-05
            y: 1.0e-05
            z: 1.0e-05
      - id: 20
        size: 1.0
        pose:
          position:
            x: -2.35
            y: -1.5
            z: 1.5
          rotation:
            x: 1.57
            y: 0
            z: 0
          position_noise:
            x: 0.0001
            y: 0.0001
            z: 0.0001
          rotation_noise:
            x: 1.0e-05
            y: 1.0e-05
            z: 1.0e-05
 - rig:
     is_static: false
     type: simple
     odom_topic: "/odom"
     odom_frame_id: base_footprint
    #  T_body_odom:
    #   position:
    #     x:  -1.05
    #     y:  11.66
    #     z:  2.5
    #   rotation:
    #     x:  0.0
    #     y:  0.0
    #     z:  0.0
```
